[package]
name = "hit-with-gpt"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
bincode = "1"
clap = { version = "4.0", features = ["derive"] }
notify = "6"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1"

[dev-dependencies]
httpmock = "0.6"

[[bin]]
name = "hit"
path = "src/main.rs"
